export const gameDetails = [
  {
    game_code: "4",
    game_name: "Crash Touchdown",
    game_img:
      "https://softapi2.shop/uploads/games/crash-touchdown-014c49675e1c22c76352b8047ae6d8eb.png",
    category: "flash",
    gameID: "4",
    gameNameEn: "Crash Touchdown",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "17",
    game_name: "Devil Fire 2",
    game_img:
      "https://softapi2.shop/uploads/games/devil-fire-2-0426ba674c9dd29de6fa023afcf0640d.png",
    category: "flash",
    gameID: "17",
    gameNameEn: "Devil Fire 2",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "21",
    game_name: "Caribbean Stud Poker",
    game_img:
      "https://softapi2.shop/uploads/games/caribbean-stud-poker-04c9784b0b1b162b2c86f9ce353da8b7.png",
    category: "flash",
    gameID: "21",
    gameNameEn: "Caribbean Stud Poker",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "26",
    game_name: "Golden Land",
    game_img:
      "https://softapi2.shop/uploads/games/golden-land-05fc951a633d4c6b4bbe8c429cd63658.png",
    category: "flash",
    gameID: "26",
    gameNameEn: "Golden Land",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "33",
    game_name: "MINI FLUSH",
    game_img:
      "https://softapi2.shop/uploads/games/mini-flush-07afefc388ab6af8cf26f85286f83fae.png",
    category: "flash",
    gameID: "33",
    gameNameEn: "MINI FLUSH",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "42",
    game_name: "Fengshen",
    game_img:
      "https://softapi2.shop/uploads/games/fengshen-09699fd0de13edbb6c4a194d7494640b.png",
    category: "slot",
    gameID: "42",
    gameNameEn: "Fengshen",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "44",
    game_name: "Pearls of Bingo",
    game_img:
      "https://softapi2.shop/uploads/games/pearls-of-bingo-0995142f4685f66dfdd1a54fffa66ffa.png",
    category: "flash",
    gameID: "44",
    gameNameEn: "Pearls of Bingo",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "53",
    game_name: "Journey West M",
    game_img:
      "https://softapi2.shop/uploads/games/journey-west-m-0d0a5a1731a6a05ffeb0e0f9d1948f80.png",
    category: "flash",
    gameID: "53",
    gameNameEn: "Journey West M",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "59",
    game_name: "Super Ace Scratch",
    game_img:
      "https://softapi2.shop/uploads/games/super-ace-scratch-0ec0aeb7aad8903bb6ee6b9b9460926a.png",
    category: "flash",
    gameID: "59",
    gameNameEn: "Super Ace Scratch",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "75",
    game_name: "JILI CAISHEN",
    game_img:
      "https://softapi2.shop/uploads/games/jili-caishen-11e330c2b23f106815f3b726d04e4316.png",
    category: "flash",
    gameID: "75",
    gameNameEn: "JILI CAISHEN",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "76",
    game_name: "Dragon Fortune",
    game_img:
      "https://softapi2.shop/uploads/games/dragon-fortune-1200b82493e4788d038849bca884d773.png",
    category: "fish",
    gameID: "76",
    gameNameEn: "Dragon Fortune",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "82",
    game_name: "Legacy of Egypt",
    game_img:
      "https://softapi2.shop/uploads/games/legacy-of-egypt-1310248a5eab24b4bf113a6e0ee7962a.png",
    category: "flash",
    gameID: "82",
    gameNameEn: "Legacy of Egypt",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "104",
    game_name: "Keno Extra Bet",
    game_img:
      "https://softapi2.shop/uploads/games/keno-extra-bet-191d02a6e852cd18ce1dd4d175e96cd6.png",
    category: "flash",
    gameID: "104",
    gameNameEn: "Keno Extra Bet",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "107",
    game_name: "TeenPatti Joker",
    game_img:
      "https://softapi2.shop/uploads/games/teenpatti-joker-1a4eaca67612e65fdcae43f4c8a667a4.png",
    category: "flash",
    gameID: "107",
    gameNameEn: "TeenPatti Joker",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "110",
    game_name: "TeenPatti 20-20",
    game_img:
      "https://softapi2.shop/uploads/games/teenpatti-20-20-1afa7db588d05de7b9abca4664542765.png",
    category: "flash",
    gameID: "110",
    gameNameEn: "TeenPatti 20-20",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "113",
    game_name: "Devil Fire",
    game_img:
      "https://softapi2.shop/uploads/games/devil-fire-1b4c5865131b4967513c1ee90cba4472.png",
    category: "flash",
    gameID: "113",
    gameNameEn: "Devil Fire",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "119",
    game_name: "Secret Treasure",
    game_img:
      "https://softapi2.shop/uploads/games/secret-treasure-1d1f267e3a078ade8e5ccd56582ac94f.png",
    category: "slot",
    gameID: "119",
    gameNameEn: "Secret Treasure",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "128",
    game_name: "Happy Taxi",
    game_img:
      "https://softapi2.shop/uploads/games/happy-taxi-1ed896aae4bdc78c984021307b1dd177.png",
    category: "slot",
    gameID: "128",
    gameNameEn: "Happy Taxi",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "142",
    game_name: "God Of Martial",
    game_img:
      "https://softapi2.shop/uploads/games/god-of-martial-21ef8a7ddd39836979170a2e7584e333.png",
    category: "slot",
    gameID: "142",
    gameNameEn: "God Of Martial",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "148",
    game_name: "Bingo Adventure",
    game_img:
      "https://softapi2.shop/uploads/games/bingo-adventure-2303867628a9a62272da7576665bbc65.png",
    category: "flash",
    gameID: "148",
    gameNameEn: "Bingo Adventure",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "155",
    game_name: "Boxing Extravaganza",
    game_img:
      "https://softapi2.shop/uploads/games/boxing-extravaganza-2469a7a4bdf296f841f59d0a42bba1a8.png",
    category: "flash",
    gameID: "155",
    gameNameEn: "Boxing Extravaganza",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "158",
    game_name: "Chin Shi Huang",
    game_img:
      "https://softapi2.shop/uploads/games/chin-shi-huang-24da72b49b0dd0e5cbef9579d09d8981.png",
    category: "slot",
    gameID: "158",
    gameNameEn: "Chin Shi Huang",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "162",
    game_name: "Big Small",
    game_img:
      "https://softapi2.shop/uploads/games/big-small-25822eb4d6459cc8b39c4f7b69b1bf2c.png",
    category: "flash",
    gameID: "162",
    gameNameEn: "Big Small",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "163",
    game_name: "3 Coin Wild Horse",
    game_img:
      "https://softapi2.shop/uploads/games/3-coin-wild-horse-25bff08b69ccd31c238a627b53afff36.png",
    category: "flash",
    gameID: "163",
    gameNameEn: "3 Coin Wild Horse",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "170",
    game_name: "Tongits Go",
    game_img:
      "https://softapi2.shop/uploads/games/tongits-go-26fbfab92a3837b7dbf767e783b173af.png",
    category: "flash",
    gameID: "170",
    gameNameEn: "Tongits Go",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "177",
    game_name: "World Cup",
    game_img:
      "https://softapi2.shop/uploads/games/world-cup-28374b7ad7c91838a46404f1df046e5a.png",
    category: "slot",
    gameID: "177",
    gameNameEn: "World Cup",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "182",
    game_name: "Charge Buffalo Ascent",
    game_img:
      "https://softapi2.shop/uploads/games/charge-buffalo-ascent-28bc4a33c985ddce6acd92422626b76f.png",
    category: "flash",
    gameID: "182",
    gameNameEn: "Charge Buffalo Ascent",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "183",
    game_name: "Video Poker",
    game_img:
      "https://softapi2.shop/uploads/games/video-poker-28d459e6b8bba9a375e65e1f25e8d316.png",
    category: "flash",
    gameID: "183",
    gameNameEn: "Video Poker",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "185",
    game_name: "Jogo do Bicho",
    game_img:
      "https://softapi2.shop/uploads/games/jogo-do-bicho-29149ed003ec05873fc164fc139b5606.png",
    category: "flash",
    gameID: "185",
    gameNameEn: "Jogo do Bicho",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "189",
    game_name: "Super Ace Joker",
    game_img:
      "https://softapi2.shop/uploads/games/super-ace-joker-29c66f73e3916b8eb18c2bf78886927d.png",
    category: "flash",
    gameID: "189",
    gameNameEn: "Super Ace Joker",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "192",
    game_name: "Gold Rush",
    game_img:
      "https://softapi2.shop/uploads/games/gold-rush-2a5d731e0fd60f52873a24ece11f2c0b.png",
    category: "slot",
    gameID: "192",
    gameNameEn: "Gold Rush",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "193",
    game_name: "Color Game",
    game_img:
      "https://softapi2.shop/uploads/games/color-game-2ac4917fbc8b2034307b0c3cdd90d416.png",
    category: "flash",
    gameID: "193",
    gameNameEn: "Color Game",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "195",
    game_name: "Crash Cricket",
    game_img:
      "https://softapi2.shop/uploads/games/crash-cricket-2b3e6d31620ceabbe44d3edb6fd10af3.png",
    category: "flash",
    gameID: "195",
    gameNameEn: "Crash Cricket",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "197",
    game_name: "Medusa",
    game_img:
      "https://softapi2.shop/uploads/games/medusa-2c17b7c4e2ce5b8bebf4bd10e3e958d7.png",
    category: "slot",
    gameID: "197",
    gameNameEn: "Medusa",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "202",
    game_name: "Candy Baby",
    game_img:
      "https://softapi2.shop/uploads/games/candy-baby-2cc3b68cbcfacac2f7ef2fe19abc3c22.png",
    category: "slot",
    gameID: "202",
    gameNameEn: "Candy Baby",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "211",
    game_name: "Wild Racer",
    game_img:
      "https://softapi2.shop/uploads/games/wild-racer-2f0c5f96cda3c6e16b3929dd6103df8e.png",
    category: "slot",
    gameID: "211",
    gameNameEn: "Wild Racer",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "216",
    game_name: "Fortune Bingo",
    game_img:
      "https://softapi2.shop/uploads/games/fortune-bingo-2fd70535a3c838a438b4b8003ecce49d.png",
    category: "flash",
    gameID: "216",
    gameNameEn: "Fortune Bingo",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "245",
    game_name: "Number King",
    game_img:
      "https://softapi2.shop/uploads/games/number-king-36d20c24669dca7630715f2e0a7c18be.png",
    category: "flash",
    gameID: "245",
    gameNameEn: "Number King",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "257",
    game_name: "Bonus Hunter",
    game_img:
      "https://softapi2.shop/uploads/games/bonus-hunter-39775cdc4170e56c5f768bdee8b4fa00.png",
    category: "slot",
    gameID: "257",
    gameNameEn: "Bonus Hunter",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "259",
    game_name: "Jhandi Munda",
    game_img:
      "https://softapi2.shop/uploads/games/jhandi-munda-3a2f7e03e9e86c925ab8c8612f2ea259.png",
    category: "flash",
    gameID: "259",
    gameNameEn: "Jhandi Munda",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "261",
    game_name: "Money Coming Expand Bets",
    game_img:
      "https://softapi2.shop/uploads/games/money-coming-expand-bets-3a557646c3abb12201c0b8810a8c0966.png",
    category: "flash",
    gameID: "261",
    gameNameEn: "Money Coming Expand Bets",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "262",
    game_name: "Golden Bank 2",
    game_img:
      "https://softapi2.shop/uploads/games/golden-bank-2-3a72a27c8851be5a396f51a19654c7c3.png",
    category: "flash",
    gameID: "262",
    gameNameEn: "Golden Bank 2",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "264",
    game_name: "7up7down",
    game_img:
      "https://softapi2.shop/uploads/games/7up7down-3aca3084a5c1a8c77c52d6147ee3d2ab.png",
    category: "flash",
    gameID: "264",
    gameNameEn: "7up7down",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "267",
    game_name: "Blackjack",
    game_img:
      "https://softapi2.shop/uploads/games/blackjack-3b502aee6c9e1ef0f698332ee1b76634.png",
    category: "flash",
    gameID: "267",
    gameNameEn: "Blackjack",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "270",
    game_name: "Jackpot Fishing",
    game_img:
      "https://softapi2.shop/uploads/games/jackpot-fishing-3cf4a85cb6dcf4d8836c982c359cd72d.png",
    category: "flash",
    gameID: "270",
    gameNameEn: "Jackpot Fishing",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "296",
    game_name: "Pool Rummy",
    game_img:
      "https://softapi2.shop/uploads/games/pool-rummy-43e7df819bf57722a8917bb328640b30.png",
    category: "flash",
    gameID: "296",
    gameNameEn: "Pool Rummy",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "299",
    game_name: "Penalty Kick",
    game_img:
      "https://softapi2.shop/uploads/games/penalty-kick-446de3502193f08cdf0c17bf0791eb41.png",
    category: "flash",
    gameID: "299",
    gameNameEn: "Penalty Kick",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "306",
    game_name: "Go For Champion",
    game_img:
      "https://softapi2.shop/uploads/games/go-for-champion-45a2a090dd3f8c5e51a20e5f7c24830b.png",
    category: "flash",
    gameID: "306",
    gameNameEn: "Go For Champion",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "315",
    game_name: "Pirate Queen 2",
    game_img:
      "https://softapi2.shop/uploads/games/pirate-queen-2-4702eb871271aa62ef3f3d78f5d968c1.png",
    category: "flash",
    gameID: "315",
    gameNameEn: "Pirate Queen 2",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
  {
    game_code: "324",
    game_name: "AK47",
    game_img:
      "https://softapi2.shop/uploads/games/ak47-488c377662cad37a551bde18e2fbe785.png",
    category: "flash",
    gameID: "324",
    gameNameEn: "AK47",
    vendorId: 17,
    vendorCode: "NULL",
    customGameType: 0,
  },
];
